[project]
name = "devseeker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "flask>=3.1.0",
    "requests>=2.32.3",
    "selenium>=4.28.1",
    "waitress>=3.0.2",
]
